m = float(input('digite o valor em metros a ser convertido:'))
c = float(m*100)
ml = float(m*1000)
print('{} metros equivale a {} centímetros!'.format(m, c))
print('{} metros equivale a {} milímetros!'.format(m, ml))
